// 经典文本来源

export const WIKISOURCE_ZHOUYI = 'https://zh.wikisource.org/wiki/周易'

export const SOURCE_REFS: Record<number, string[]> = {
  1: ['https://zh.wikisource.org/wiki/周易/乾'],  // 乾
  2: ['https://zh.wikisource.org/wiki/周易/坤'],  // 坤
  3: ['https://zh.wikisource.org/wiki/周易/屯'],  // 屯
  4: ['https://zh.wikisource.org/wiki/周易/蒙'],  // 蒙
  5: ['https://zh.wikisource.org/wiki/周易/需'],  // 需
  6: ['https://zh.wikisource.org/wiki/周易/訟'],  // 訟
  7: ['https://zh.wikisource.org/wiki/周易/師'],  // 師
  8: ['https://zh.wikisource.org/wiki/周易/比'],  // 比
  9: ['https://zh.wikisource.org/wiki/周易/小畜'],  // 小畜
  10: ['https://zh.wikisource.org/wiki/周易/履'],  // 履
  11: ['https://zh.wikisource.org/wiki/周易/泰'],  // 泰
  12: ['https://zh.wikisource.org/wiki/周易/否'],  // 否
  13: ['https://zh.wikisource.org/wiki/周易/同人'],  // 同人
  14: ['https://zh.wikisource.org/wiki/周易/大有'],  // 大有
  15: ['https://zh.wikisource.org/wiki/周易/謙'],  // 謙
  16: ['https://zh.wikisource.org/wiki/周易/豫'],  // 豫
  17: ['https://zh.wikisource.org/wiki/周易/隨'],  // 隨
  18: ['https://zh.wikisource.org/wiki/周易/蠱'],  // 蠱
  19: ['https://zh.wikisource.org/wiki/周易/臨'],  // 臨
  20: ['https://zh.wikisource.org/wiki/周易/觀'],  // 觀
  21: ['https://zh.wikisource.org/wiki/周易/噬嗑'],  // 噬嗑
  22: ['https://zh.wikisource.org/wiki/周易/賁'],  // 賁
  23: ['https://zh.wikisource.org/wiki/周易/剝'],  // 剝
  24: ['https://zh.wikisource.org/wiki/周易/復'],  // 復
  25: ['https://zh.wikisource.org/wiki/周易/无妄'],  // 无妄
  26: ['https://zh.wikisource.org/wiki/周易/大畜'],  // 大畜
  27: ['https://zh.wikisource.org/wiki/周易/頤'],  // 頤
  28: ['https://zh.wikisource.org/wiki/周易/大過'],  // 大過
  29: ['https://zh.wikisource.org/wiki/周易/坎'],  // 坎
  30: ['https://zh.wikisource.org/wiki/周易/離'],  // 離
  31: ['https://zh.wikisource.org/wiki/周易/咸'],  // 咸
  32: ['https://zh.wikisource.org/wiki/周易/恆'],  // 恆
  33: ['https://zh.wikisource.org/wiki/周易/遯'],  // 遯
  34: ['https://zh.wikisource.org/wiki/周易/大壯'],  // 大壯
  35: ['https://zh.wikisource.org/wiki/周易/晉'],  // 晉
  36: ['https://zh.wikisource.org/wiki/周易/明夷'],  // 明夷
  37: ['https://zh.wikisource.org/wiki/周易/家人'],  // 家人
  38: ['https://zh.wikisource.org/wiki/周易/睽'],  // 睽
  39: ['https://zh.wikisource.org/wiki/周易/蹇'],  // 蹇
  40: ['https://zh.wikisource.org/wiki/周易/解'],  // 解
  41: ['https://zh.wikisource.org/wiki/周易/損'],  // 損
  42: ['https://zh.wikisource.org/wiki/周易/益'],  // 益
  43: ['https://zh.wikisource.org/wiki/周易/夬'],  // 夬
  44: ['https://zh.wikisource.org/wiki/周易/姤'],  // 姤
  45: ['https://zh.wikisource.org/wiki/周易/萃'],  // 萃
  46: ['https://zh.wikisource.org/wiki/周易/升'],  // 升
  47: ['https://zh.wikisource.org/wiki/周易/困'],  // 困
  48: ['https://zh.wikisource.org/wiki/周易/井'],  // 井
  49: ['https://zh.wikisource.org/wiki/周易/革'],  // 革
  50: ['https://zh.wikisource.org/wiki/周易/鼎'],  // 鼎
  51: ['https://zh.wikisource.org/wiki/周易/震'],  // 震
  52: ['https://zh.wikisource.org/wiki/周易/艮'],  // 艮
  53: ['https://zh.wikisource.org/wiki/周易/漸'],  // 漸
  54: ['https://zh.wikisource.org/wiki/周易/歸妹'],  // 歸妹
  55: ['https://zh.wikisource.org/wiki/周易/豐'],  // 豐
  56: ['https://zh.wikisource.org/wiki/周易/旅'],  // 旅
  57: ['https://zh.wikisource.org/wiki/周易/巽'],  // 巽
  58: ['https://zh.wikisource.org/wiki/周易/兌'],  // 兌
  59: ['https://zh.wikisource.org/wiki/周易/渙'],  // 渙
  60: ['https://zh.wikisource.org/wiki/周易/節'],  // 節
  61: ['https://zh.wikisource.org/wiki/周易/中孚'],  // 中孚
  62: ['https://zh.wikisource.org/wiki/周易/小過'],  // 小過
  63: ['https://zh.wikisource.org/wiki/周易/既濟'],  // 既濟
  64: ['https://zh.wikisource.org/wiki/周易/未濟'],  // 未濟
}
